configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/download_paper_data.smk"
include: "rules/extract_ground_truth.smk"
include: "rules/extract_2024_bayesspace.smk"
include: "rules/run_bayesspace.smk"
include: "rules/run_mclust.smk"
include: "rules/make_comparison_manifest.smk"
include: "rules/run_comparisons.smk"



rule all:
    input:
        # Download all sample data
        [f"resources/paper_data/{year}/{sample}.RData" for year, sample in all_samples],

        # Extract all available ground truth data
        [f"results/ground_truths/{year}/{sample}.csv" for year, sample in ground_truth_samples],

        # Extract all available clustering data from 2024 BayesSpace
        [f"results/cluster_assignments/2024/paper_bayesspace/{sample}.csv" for year, sample in all_samples if year == "2024"],

        # Run BayesSpace clustering for all samples
        [get_bayesspace_outputs(year, sample) for year, sample in all_samples],

        # Run Mclust clustering for all samples
        [get_mclust_outputs(year, sample) for year, sample in all_samples],

        # Create the comparison manifest
        "results/comparisons/comparison_manifest.csv",

        # Run the comparison
        "results/comparisons/.done",
