configfile: "config/config.yaml"
all_samples = [(year, sample) for year in config["samples"].keys() for sample in config["samples"][year]]
ground_truth_samples = [(year, sample) for year in config["ground_truth_samples"].keys() for sample in config["ground_truth_samples"][year]]
rule all:
    input:
        # Downloaded .RData files
        [f"resources/paper_data/{year}/{sample}.RData" for year, sample in all_samples],
        # Extracted ground truth files
        [f"results/ground_truths/{year}/{sample}.csv" for year, sample in ground_truth_samples]

include: "rules/download_paper_data.smk"
include: "rules/ground_truth.smk"