services:
  dev-container:
    # image: clarity001/bioinformatics:latest
    image: autumnusomega/bioinformatics:cluster-comparison
    build: .
    container_name: vscode-container
    volumes:
      - /zata:/zata
      - /data:/data
    stdin_open: true
    working_dir: /zata/zippy/kresgeb
    tty: true
    restart: unless-stopped