services:
  dev-container:
    image: autumnusomega/bioinformatics:nmf-stuff
    # build: .
    container_name: nmf-stuff-dev-container
    volumes:
      - /zata:/zata
      - /data:/data
    stdin_open: true
    working_dir: /zata/zippy/kresgeb
    tty: true
    restart: unless-stopped